//! Static analysis for Soroban smart contracts.
//!
//! `soroban-analyzer` reads a contract's Rust source and reports patterns that are
//! known to be bugs *on Soroban specifically*, with the things general Rust tooling
//! cannot know: that `require_auth` is the only thing standing between a privileged
//! entrypoint and anyone who can pay for the call, that temporary storage is reclaimed
//! and persistent storage is not, that an invocation may read at most 200 ledger
//! entries, and that arithmetic on an amount traps rather than wrapping because
//! contracts deploy with overflow checks on.
//!
//! It is the static-analysis half of the Soroban Static Analysis & Fuzzing Toolkit,
//! and it is designed around one contribution at a time: **one detector per pull
//! request**, each with its own fixtures.
//!
//! # What a check needs to be a detector
//!
//! A detector is two files:
//!
//! * `src/detectors/<id>.rs` — a struct implementing [`Detector`], saying what shape to
//!   look for;
//! * `rules/<id>.json` — the rule metadata: title, severity, rationale, remediation,
//!   references, and **two source snippets, one that must trigger the rule and one that
//!   must not**.
//!
//! Neither file is optional, and the snippets are not documentation. The crate's tests
//! parse and run every rule's own examples on every commit, so a detector that fires on
//! its clean example, or not on its triggering one, fails the build. That is how the
//! contribution standard — *a detector with no fixture proving it fires, and one
//! proving it does not over-fire, is not mergeable* — is enforced rather than merely
//! written down.
//!
//! Neither file requires an edit to any shared list: the registry is generated at build
//! time from the contents of those two directories.
//!
//! # Use from a test
//!
//! ```
//! use soroban_analyzer::{Analyzer, SourceFile};
//!
//! let analyzer = Analyzer::embedded();
//! let file = SourceFile::parse(
//!     "contract.rs",
//!     r#"
//! # use soroban_sdk::{contract, contractimpl, Env, Symbol, Address};
//! #[contract]
//! pub struct Fee;
//! #[contractimpl]
//! impl Fee {
//!     // No authorization anywhere, and instance storage is written.
//!     pub fn set_fee_bps(env: Env, bps: u32) {
//!         env.storage().instance().set(&Symbol::new(&env, "fee"), &bps);
//!     }
//! }
//! # "#.to_owned(),
//! )
//! .expect("the fixture parses");
//!
//! let found = analyzer.check_file(&file);
//! assert!(found
//!     .findings
//!     .iter()
//!     .any(|finding| finding.rule == "soroban-missing-require-auth"));
//! ```
//!
//! # Grading, and the exit status
//!
//! A finding's severity, rationale and remediation come from its rule, never from the
//! detector that reported it, so adding a detector cannot quietly re-grade an existing
//! pattern. Severities run from [`Severity::Info`] to [`Severity::Critical`], and the
//! binary exits non-zero when a finding at or above a threshold is present.
//!
//! # Deliberate exceptions
//!
//! A pattern that is correct in context is excused in the code with a marker comment
//! next to it — see [`suppress`] — and suppressed findings are counted and reported
//! rather than dropped, so a run never quietly loses one.
//!
//! # Limits
//!
//! These are syntactic checks over parsed source. They do not evaluate types, do not
//! follow calls across files, and do not look at the compiled Wasm. Each rule's
//! rationale states what it assumes; where an assumption cannot be checked, the rule
//! says so instead of guessing.

#![warn(missing_docs)]
#![warn(rustdoc::broken_intra_doc_links)]
#![forbid(unsafe_code)]

/// The tool's name, as it appears in reports, SARIF and the command line.
pub const TOOL_NAME: &str = "soroban-analyze";

/// This build's version, taken from the manifest so the two cannot disagree.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Where the tool lives, which SARIF consumers use to link a finding to its rule.
pub const REPOSITORY: &str = env!("CARGO_PKG_REPOSITORY");

use std::path::{Path, PathBuf};

pub mod baseline;
pub mod config;
pub mod detector;
pub mod detectors;
pub mod finding;
pub mod report;
pub mod rules;
pub mod severity;
pub mod source;
pub mod suppress;
pub mod syntax;
pub mod walk;

pub use baseline::Baseline;
pub use config::Config;
pub use detector::{load_embedded_rules, Analyzer, Detector, FileFindings};
pub use finding::Finding;
pub use report::{Format, Report};
pub use rules::{Rule, RuleError, RuleSet};
pub use severity::Severity;
pub use source::{Location, Position, SourceFile};

/// The rule metadata and detector registry generated by `build.rs` at build time.
///
/// Not part of the public API: it exists so [`RuleSet::embedded`] and
/// [`detectors::all`] can be written against generated code without exposing it.
mod rules_index {
    include!(concat!(env!("OUT_DIR"), "/rule_index.rs"));
}

/// One file's outcome, before the results are merged.
enum Outcome {
    /// The file was read and checked.
    Analysed(FileFindings),
    /// The file could not be read or parsed, with the reason.
    Unreadable(String),
}

/// Analyses a directory or a single file, on one thread.
///
/// A thin convenience over [`walk`] and [`Analyzer::check_file`] for callers that just
/// want the findings: files that fail to parse are reported separately rather than
/// aborting the run, because one unparseable file in a workspace should not stop the
/// rest from being analysed.
pub fn analyze_path(
    analyzer: &Analyzer,
    path: impl AsRef<Path>,
) -> (Vec<Finding>, Vec<Finding>, Vec<String>) {
    analyze_paths(analyzer, &[path.as_ref().to_path_buf()], 1)
}

/// Analyses every file under `paths` using up to `jobs` threads.
///
/// Parallelism is worth having because the work is one file at a time and the cost is
/// parsing, which is pure CPU: a crate with a few hundred source files is a few hundred
/// independent parses, and the analyser's own CI runs it over a vendored contract on
/// every push. What it must not cost is determinism, so the files are ordered here, the
/// results are merged back in that order, and the reports sort what they render. Two runs
/// over the same tree produce the same bytes whether `jobs` is 1 or 64.
///
/// `jobs` is a ceiling, not a promise: the number of threads is capped at the number of
/// files, so a one-file run does not pay for a thread pool. A caller that wants the
/// single-threaded behaviour can pass 1, and a caller that does not care can pass
/// [`std::thread::available_parallelism`].
///
/// Detectors must be [`Send`] and [`Sync`] for this, which is why [`Detector`] requires
/// it: an engine that can only run on one core is an engine whose cost grows with the
/// tree it is pointed at.
pub fn analyze_paths(
    analyzer: &Analyzer,
    paths: &[PathBuf],
    jobs: usize,
) -> (Vec<Finding>, Vec<Finding>, Vec<String>) {
    let mut files = Vec::new();
    let mut problems = Vec::new();
    for path in paths {
        let (found, skipped) = walk::collect(path);
        files.extend(found);
        problems.extend(skipped);
    }
    // Sorted and deduplicated before anything is read, so that naming a directory and a
    // file inside it does not analyse that file twice, and so that the parallel merge
    // below has one canonical order to restore.
    files.sort();
    files.dedup();

    let next = std::sync::atomic::AtomicUsize::new(0);
    let outcomes = std::sync::Mutex::new(Vec::with_capacity(files.len()));
    let workers = jobs.clamp(1, files.len().max(1));

    let analyse = |index: usize| -> (usize, Outcome) {
        let path = &files[index];
        let outcome = match SourceFile::read(path) {
            Ok(file) => Outcome::Analysed(analyzer.check_file(&file)),
            Err(error) => Outcome::Unreadable(format!("{}: {error}", path.display())),
        };
        (index, outcome)
    };

    if workers > 1 {
        std::thread::scope(|scope| {
            for _ in 0..workers {
                scope.spawn(|| loop {
                    let index = next.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                    if index >= files.len() {
                        break;
                    }
                    let result = analyse(index);
                    // Poisoning is ignored rather than propagated: a panic is already
                    // being reported by the thread that caused it, and a detector that
                    // panicked on one file must not also lose every other file's work.
                    outcomes
                        .lock()
                        .unwrap_or_else(|poisoned| poisoned.into_inner())
                        .push(result);
                });
            }
        });
    } else {
        for index in 0..files.len() {
            let result = analyse(index);
            outcomes
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .push(result);
        }
    }

    let mut outcomes = outcomes
        .into_inner()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    outcomes.sort_by_key(|(index, _)| *index);

    let mut findings = Vec::new();
    let mut suppressed = Vec::new();
    for (_, outcome) in outcomes {
        match outcome {
            Outcome::Analysed(found) => {
                findings.extend(found.findings);
                suppressed.extend(found.suppressed);
            }
            Outcome::Unreadable(problem) => problems.push(problem),
        }
    }

    (findings, suppressed, problems)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A contract with one unprotected privileged entrypoint.
    const VULNERABLE: &str = "#[contractimpl]\nimpl Token {\n    pub fn mint(env: Env, to: Address, amount: i128) {\n        env.storage().persistent().set(&to, &amount);\n    }\n}\n";

    /// A tree of `count` vulnerable files, named after the test that made it.
    fn scratch(name: &str, count: usize) -> PathBuf {
        let root = std::env::temp_dir().join(format!("soroban-analyzer-analyze-paths-{name}"));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("src")).expect("the scratch directory can be made");
        for index in 0..count {
            std::fs::write(root.join(format!("src/file{index:02}.rs")), VULNERABLE)
                .expect("the fixture can be written");
        }
        root
    }

    /// The findings as comparable identities, in a fixed order.
    fn described(findings: &[Finding]) -> Vec<String> {
        let mut described = findings
            .iter()
            .map(|finding| {
                format!(
                    "{}:{}:{}",
                    finding.file, finding.location.start.line, finding.rule
                )
            })
            .collect::<Vec<_>>();
        described.sort();
        described
    }

    #[test]
    fn the_thread_count_changes_nothing_about_the_result() {
        // The property that makes `--jobs` safe to expose: a run is a function of the
        // tree, not of how many threads happened to read it.
        let root = scratch("same-result", 12);
        let analyzer = Analyzer::embedded();

        let single = analyze_paths(&analyzer, std::slice::from_ref(&root), 1);
        let parallel = analyze_paths(&analyzer, std::slice::from_ref(&root), 8);

        assert!(!single.0.is_empty(), "the fixtures must produce findings");
        assert_eq!(described(&single.0), described(&parallel.0));
        assert_eq!(single.1.len(), parallel.1.len());
        assert_eq!(single.2, parallel.2);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_file_named_twice_is_analysed_once() {
        // `soroban-analyze src src/lib.rs` is a reasonable thing to type, and reporting
        // every finding twice is not a reasonable answer.
        let root = scratch("duplicates", 3);
        let analyzer = Analyzer::embedded();
        let paths = vec![root.clone(), root.join("src/file00.rs")];

        let (findings, _, problems) = analyze_paths(&analyzer, &paths, 4);
        assert!(problems.is_empty(), "{problems:?}");
        let described = described(&findings);
        let mut unique = described.clone();
        unique.dedup();
        assert_eq!(described.len(), unique.len(), "{described:?}");
        assert_eq!(described.len(), 3, "one finding per file: {described:?}");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn zero_jobs_is_clamped_rather_than_refused_or_hanging() {
        // The CLI rejects `--jobs 0`; the library clamps, because a caller that computed
        // a thread count of zero wants a run, not a panic.
        let root = scratch("zero-jobs", 2);
        let analyzer = Analyzer::embedded();
        let (findings, _, problems) = analyze_paths(&analyzer, std::slice::from_ref(&root), 0);
        assert_eq!(problems, Vec::<String>::new());
        assert_eq!(described(&findings).len(), 2);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_file_that_cannot_be_read_is_a_problem_from_any_thread() {
        // The merge has to keep the distinction between "found nothing" and "could not
        // look", whichever thread did the looking.
        let root = scratch("unreadable", 2);
        std::fs::write(root.join("src/broken.rs"), "pub fn oops( {\n")
            .expect("the fixture can be written");
        let analyzer = Analyzer::embedded();

        let (findings, _, problems) = analyze_paths(&analyzer, std::slice::from_ref(&root), 4);
        assert_eq!(findings.len(), 2, "the readable files are still analysed");
        assert_eq!(problems.len(), 1, "{problems:?}");
        assert!(problems[0].contains("broken.rs"), "{problems:?}");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn an_empty_tree_is_a_result_rather_than_a_division_by_zero() {
        let root = scratch("empty", 0);
        let analyzer = Analyzer::embedded();
        let (findings, suppressed, problems) =
            analyze_paths(&analyzer, std::slice::from_ref(&root), 8);
        assert!(findings.is_empty());
        assert!(suppressed.is_empty());
        assert!(problems.is_empty());
        let _ = std::fs::remove_dir_all(&root);
    }
}
