//! Generates the detector registry and the rule metadata index from the files on disk.
//!
//! The contribution model for this crate is one detector per pull request, and that is
//! only true if adding one requires no edit to shared code. A hand-maintained list
//! would make every detector pull request conflict with every other, so the list is
//! derived from the filesystem instead: dropping `src/detectors/<id>.rs` and
//! `rules/<id>.json` into the tree is the whole change.
//!
//! Two things are emitted, both into `OUT_DIR` so nothing generated is ever committed:
//!
//! * `detector_registry.rs` — one inline module per detector file, and the `all()`
//!   function that returns instances of each. Files are sorted, so the output is
//!   deterministic and a run's finding order does not depend on the filesystem.
//! * `rule_index.rs` — the rule metadata files, embedded with `include_str!` so the
//!   binary carries its own rules and does not depend on the source tree at runtime.
//!
//! Nothing here validates the *content* of a rule file. That happens in the crate's
//! tests, where a failure names the offending rule; a build script that refuses to
//! compile would make it impossible to run those tests while writing one.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const DETECTOR_DIR: &str = "src/detectors";
const RULE_DIR: &str = "rules";
const REGISTRY_FILE: &str = "detector_registry.rs";
const RULE_INDEX_FILE: &str = "rule_index.rs";

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this"));

    let detectors = files_with_extension(&manifest_dir.join(DETECTOR_DIR), "rs")
        .into_iter()
        .filter(|path| path.file_name().is_some_and(|name| name != "mod.rs"))
        .collect::<Vec<_>>();
    let rules = files_with_extension(&manifest_dir.join(RULE_DIR), "json");

    // A rule file changing must rebuild the binary that embeds it, and a detector file
    // appearing must re-emit the registry.
    println!("cargo:rerun-if-changed={DETECTOR_DIR}");
    println!("cargo:rerun-if-changed={RULE_DIR}");

    write(&out_dir.join(REGISTRY_FILE), &detector_registry(&detectors));
    write(&out_dir.join(RULE_INDEX_FILE), &rule_index(&rules));
}

/// Sorted paths of the files in `dir` with the given extension, or none if it does not
/// exist. An absent directory is not an error: a crate with no detectors should build.
fn files_with_extension(dir: &Path, extension: &str) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut paths = entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == extension))
        .collect::<Vec<_>>();
    paths.sort();
    paths
}

/// `pub mod <name> { include!("<abs path>"); }` for each detector, plus `all()`.
///
/// The detector files are pulled in with an absolute path so that the generated module
/// does not depend on where the generated file happens to live. `include!` rather than
/// `#[path]`, because the manifest directory is an absolute path that contains
/// backslashes on Windows and a `#[path]` attribute is a string literal.
///
/// One consequence is worth knowing for anyone writing a detector: a detector file must
/// not open with `//!` module documentation, because rustc rejects inner attributes that
/// arrive through a macro expansion — `error[E0753]: expected outer doc comment`, once
/// per line. Detector files therefore explain themselves with ordinary `//` comments,
/// and the generated module below carries a short doc comment instead.
fn detector_registry(detectors: &[PathBuf]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from the contents of src/detectors.\n\n");

    let mut names = Vec::new();
    for path in detectors {
        let Some(name) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        let _ = writeln!(
            out,
            "/// Detector generated from `{DETECTOR_DIR}/{name}.rs`, which carries the\n/// reasoning for the check as ordinary comments."
        );
        let _ = writeln!(out, "pub mod {name} {{");
        let _ = writeln!(
            out,
            "    include!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{DETECTOR_DIR}/{name}.rs\"));"
        );
        let _ = writeln!(out, "}}");
        names.push(name.to_owned());
    }

    out.push_str(
        "/// Every registered detector, in a deterministic order.\n\
         ///\n\
         /// The order is the sorted detector file name, so it does not depend on the\n\
         /// filesystem and two runs on the same tree report in the same order.\n\
         pub fn all() -> Vec<Box<dyn crate::detector::Detector>> {\n    vec![\n",
    );
    for name in &names {
        let _ = writeln!(out, "        Box::new({name}::Detector),");
    }
    out.push_str("    ]\n}\n");

    // `#[cfg(test)]`, because the only thing that can observe a detector's *file name* is
    // the test that checks the registry is sorted and complete: production code uses
    // `all()`. A constant nothing reads in a release build is dead code, and this
    // workspace denies dead code in CI.
    let _ = writeln!(
        out,
        "\n/// The detector file names this registry was generated from.\n\
         #[cfg(test)]\n\
         pub const DETECTOR_MODULES: &[&str] = &[{}];",
        names
            .iter()
            .map(|name| format!("\"{name}\""))
            .collect::<Vec<_>>()
            .join(", ")
    );

    out
}

/// The rule metadata files, as `include_str!`d sources, plus their names.
fn rule_index(rules: &[PathBuf]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from the contents of rules.\n\n");

    out.push_str("/// The embedded rule metadata files, in sorted order.\npub const RULE_SOURCES: &[&str] = &[\n");
    for path in rules {
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        let _ = writeln!(
            out,
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{RULE_DIR}/{name}\")),"
        );
    }
    out.push_str("];\n\n");

    out.push_str("/// The file name of each rule, aligned with [`RULE_SOURCES`].\npub const RULE_NAMES: &[&str] = &[\n");
    for path in rules {
        if let Some(name) = path.file_name().and_then(|name| name.to_str()) {
            let _ = writeln!(out, "    \"{name}\",");
        }
    }
    out.push_str("];\n");

    out
}

/// Writes `contents` to `path`, failing the build loudly if it cannot.
fn write(path: &Path, contents: &str) {
    if let Err(err) = fs::write(path, contents) {
        panic!("could not write {}: {err}", path.display());
    }
}
