//! Generating actions from `arbitrary::Arbitrary`.
//!
//! [`proptest`](https://docs.rs/proptest) and
//! [`arbitrary`](https://docs.rs/arbitrary) are both property-testing input generators,
//! and plenty of Soroban codebases already derive `Arbitrary` for their own types —
//! `soroban-sdk` itself depends on it. This module lets a target reuse those definitions
//! as a source of actions instead of writing the same strategy twice:
//!
//! ```
//! use soroban_fuzzer::prelude::*;
//! use arbitrary::Arbitrary;
//!
//! #[derive(Clone, Debug, Arbitrary)]
//! enum Act {
//!     Transfer { amount: u16, to: u8 },
//! }
//!
//! # struct MyTarget;
//! # impl Target for MyTarget {
//! #   type State = (); type Action = Act; type World = ();
//! #   fn init_state(&self) -> BoxedStrategy<()> { Just(()).boxed() }
//! #   fn setup(&self, _: &Env, _: &()) -> () {}
//! #   fn actions(&self, _: &()) -> BoxedStrategy<Act> { from_arbitrary() }
//! #   fn next_state(&self, _: (), _: &Act) -> () {}
//! #   fn execute(&self, _: &mut Runtime<'_, ()>, _: &Act) -> StepOutcome { StepOutcome::ok() }
//! # }
//! ```
//!
//! # What this costs, and when not to use it
//!
//! `Arbitrary` decodes a value from a byte stream and can *fail* — it returns
//! `Err(arbitrary::Error::NotEnoughData)` when the stream runs out, and types with
//! invariants can reject inputs outright. The adapter therefore generates bytes with
//! proptest and discards the draws that `Arbitrary` refuses.
//!
//! That rejection sampling is the trade-off. A hand-written `prop_flat_map` strategy
//! generates exactly the inputs you want and never wastes a draw; the adapter is for
//! types that already implement `Arbitrary`, where reusing the definition is worth more
//! than the wasted draws. If [`Strategy::prop_filter`] has to discard most draws, the
//! run slows down and proptest will eventually abort with "too many local rejects" —
//! which is a signal to write the strategy by hand.
//!
//! **The model's shape is not constrained by this.** Generation still has to produce
//! actions the contract can accept (see [`Target::preconditions`](crate::Target::preconditions)),
//! and a bytes-to-`Arbitrary` decoder knows nothing about your contract's state.

use core::fmt::Debug;

use arbitrary::{Arbitrary, Unstructured};
use proptest::prelude::{any, BoxedStrategy, Strategy};

/// How many bytes each draw offers to `Arbitrary::arbitrary`.
///
/// Enough for the action enums this is meant for; the length is fixed rather than
/// generated so a failure shrinks in the decoded *value* rather than merely in a
/// length prefix.
const DRAW_BYTES: usize = 128;

/// Builds a strategy that produces values by decoding them from generated bytes.
///
/// The returned strategy yields `A` values for which `A::arbitrary` succeeded, and
/// discards the draws it refused. See the module documentation for the trade-off that
/// implies.
///
/// ```
/// # use soroban_fuzzer::prelude::*;
/// # use arbitrary::Arbitrary;
/// #[derive(Clone, Debug, Arbitrary)]
/// struct Act(u8);
///
/// let strategy: BoxedStrategy<Act> = from_arbitrary();
/// # let _ = strategy;
/// ```
pub fn from_arbitrary<A>() -> BoxedStrategy<A>
where
    A: for<'a> Arbitrary<'a> + Clone + Debug + 'static,
{
    any::<[u8; DRAW_BYTES]>()
        .prop_map(|bytes: [u8; DRAW_BYTES]| {
            let mut unstructured = Unstructured::new(&bytes);
            A::arbitrary(&mut unstructured).ok()
        })
        .prop_filter("Arbitrary refused the generated bytes", Option::is_some)
        .prop_map(|value| value.expect("filtered to Some above"))
        .boxed()
}

/// Builds a strategy from an [`Arbitrary`] implementation over a *bounded* byte draw.
///
/// [`from_arbitrary`] fixes the draw length at [`DRAW_BYTES`]; this variant lets a target
/// choose it, for a type that needs more room to decode or one that decodes almost
/// anything from very few bytes.
///
/// Prefer the fixed-size version unless you have a reason: a generated length makes
/// shrinking work on two axes at once, which produces less readable reproducers.
pub fn from_arbitrary_with<A>(bytes: usize) -> BoxedStrategy<A>
where
    A: for<'a> Arbitrary<'a> + Clone + Debug + 'static,
{
    proptest::collection::vec(any::<u8>(), bytes..=bytes.max(1))
        .prop_map(move |bytes: Vec<u8>| {
            let mut unstructured = Unstructured::new(&bytes);
            A::arbitrary(&mut unstructured).ok()
        })
        .prop_filter("Arbitrary refused the generated bytes", Option::is_some)
        .prop_map(|value| value.expect("filtered to Some above"))
        .boxed()
}
